#!/bin/bash

set -eux

ROOT="$(dirname "$(readlink -f "$0")")"
MODULES="${ROOT}"/deployment_scripts/puppet/modules
RPM_REPO="${ROOT}"/repositories/centos/
DEB_REPO="${ROOT}"/repositories/ubuntu/

RALLY_INSTALLER_URL="https://raw.githubusercontent.com/openstack/rally/master/install_rally.sh"
RALLY_INSTALLER_DIR="${MODULES}"/rally/files

# Downloads needed RPM or DEB packages
function download {
    case "$1" in
        deb) REPO=$DEB_REPO;;
        rpm) REPO=$RPM_REPO;;
    esac
    shift

    while [ $# -gt 0 ]; do
        FILE=$(basename "$1")
        wget -qO - "$1" > "$REPO/$FILE"
        shift
    done
}

# Packages required for Rally installer
download deb http://mirrors.kernel.org/ubuntu/pool/main/libe/liberror-perl/liberror-perl_0.17-1.1_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/p/python-defaults/libpython-dev_2.7.5-5ubuntu3_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/libx/libxslt/libxslt1-dev_1.1.28-2build1_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/libx/libxslt/libxslt1.1_1.1.28-2build1_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/p/python-defaults/python-dev_2.7.5-5ubuntu3_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/z/zlib/zlib1g-dev_1.2.8.dfsg-1ubuntu1_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/e/e2fsprogs/comerr-dev_2.1-1.42.9-3ubuntu1.3_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/g/git/git_1.9.1-1ubuntu0.3_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/g/git/git-man_1.9.1-1ubuntu0.3_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/k/krb5/krb5-multidev_1.12+dfsg-2ubuntu5.2_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/e/expat/libexpat1-dev_2.1.0-4ubuntu1.3_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi-dev_3.1~rc1+r3.0.13-12ubuntu0.1_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/k/krb5/libgssrpc4_1.12+dfsg-2ubuntu5.2_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/k/krb5/libkadm5clnt-mit9_1.12+dfsg-2ubuntu5.2_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/k/krb5/libkadm5srv-mit9_1.12+dfsg-2ubuntu5.2_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/k/krb5/libkdb5-7_1.12+dfsg-2ubuntu5.2_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/p/postgresql-9.3/libpq-dev_9.3.13-0ubuntu0.14.04_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/p/postgresql-9.3/libpq5_9.3.13-0ubuntu0.14.04_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/p/python2.7/libpython2.7-dev_2.7.6-8ubuntu0.2_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/o/openssl/libssl-dev_1.0.1f-1ubuntu2.19_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/o/openssl/libssl-doc_1.0.1f-1ubuntu2.19_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/libx/libxml2/libxml2-dev_2.9.1+dfsg1-3ubuntu4.8_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/h/html5lib/python-html5lib_0.999-3~ubuntu1_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/h/html5lib/python-html5lib-whl_0.999-3~ubuntu1_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/r/requests/python-requests-whl_2.2.1-1ubuntu0.3_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/p/python-setuptools/python-setuptools-whl_3.3-1ubuntu2_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/s/six/python-six-whl_1.5.2-1ubuntu1_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/p/python-urllib3/python-urllib3-whl_1.7.1-1ubuntu4_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/w/wheel/python-wheel_0.24.0-1~ubuntu1_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/p/python2.7/python2.7-dev_2.7.6-8ubuntu0.2_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/p/python-setuptools/python3-pkg-resources_3.3-1ubuntu2_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/universe/c/chardet-whl/python-chardet-whl_2.2.1-2~ubuntu1_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/universe/p/python-colorama/python-colorama_0.2.5-0.1ubuntu2_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/universe/p/python-colorama/python-colorama-whl_0.2.5-0.1ubuntu2_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/universe/d/distlib/python-distlib_0.1.8-1ubuntu1_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/universe/d/distlib/python-distlib-whl_0.1.8-1ubuntu1_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/universe/p/python-pip/python-pip_1.5.4-1ubuntu4_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/universe/p/python-pip/python-pip-whl_1.5.4-1ubuntu4_all.deb

# Obtain Rally installer
mkdir -p "${RALLY_INSTALLER_DIR}"
wget -qO- "${RALLY_INSTALLER_URL}" > "${RALLY_INSTALLER_DIR}"/install_rally.sh